name: tModLoader Automatic Mod Browser Publish
author: Javid Pack (@JavidPack)
description: When build.txt is updated with new version, automatically build and publish to tModLoader Mod Browser.

inputs:
    STEAMID64:
        description: steamid64 to use for publishing. Account must be owner or maintainer of the mod.
        required: true
    MODBROWSERPASSPHRASE:
        description: Mod Browser Passphrase corresponding to the provided steamid64. Please make sure to use the Secrets in Github, do not write your passphrase in plain text in your workflow file.
        required: true

runs:
  using: "composite"
  steps: 
    - name: Print a greeting
      run: |
        echo If you see this, it is working.
        pwd
      shell: bash

    - name: Determine if build.txt is newer than Mod Browser
      run: python $GITHUB_ACTION_PATH/test.py
      shell: bash
      env:
        INPUT_STEAMID64: ${{ inputs.STEAMID64 }}
        INPUT_MODBROWSERPASSPHRASE: ${{ inputs.MODBROWSERPASSPHRASE }}
      
    - name: Build and Publish Mod if newer
      run: |
        if [ "$PUBLISH_NEEDED" != "yes" ]; then
          echo "Publish Not Needed, skipping step."
          exit
        fi
        echo Checking Mono version
        mono -V
        echo pwd is: ${PWD}
        echo ls -l is:
        ls -l
        echo CD to Home
        cd $HOME
        echo pwd is: ${PWD}
        echo ls -l is:
        ls -l
      shell: bash

branding:
    icon: server
    color: blue
