name: tModLoader Automatic Mod Browser Publish
author: Javid Pack (@JavidPack)
description: When build.txt is updated with new version, automatically build and publish to tModLoader Mod Browser.

inputs:
    steamid64:
        description: steamid64 to use for publishing. Account must be owner or maintainer of the mod.
        required: true
    modbrowserpassphrase:
        description: Mod Browser Passphrase corresponding to the provided steamid64. Please make sure to use the Secrets in Github, do not write your passphrase in plain text in your workflow file.
        required: true

runs:
  using: "composite"
  steps: 
    - name: Print a greeting
      run: |
        echo If you see this, it is working.
        pwd
      shell: bash

    - name: Test python shell command
      run: |
        import os
        import sys
        print(sys.version)
        print(os.environ['PATH'])
      shell: python

    - name: Test python script
      run: python $GITHUB_ACTION_PATH/test.py
      shell: bash
      
    - name: Print only if publishneeded
      run: |
        echo publish is needed.
        pwd
      shell: bash
      if: env.PUBLISHNEEDED == 'yes'
      
    - name: Print only if publishneeded is no
      run: |
        echo publish is not needed.
        pwd
      shell: bash
      if: env.PUBLISHNEEDED == 'no'
      
    - name: Print a goodbye
      run: |
        echo Done.
        pwd
      shell: bash

branding:
    icon: server
    color: blue
