name: tModLoader Automatic Mod Browser Publish
author: Javid Pack (@JavidPack)
description: When build.txt is updated with new version, automatically build and publish to tModLoader Mod Browser.

inputs:
    STEAMID64:
        description: steamid64 to use for publishing. Account must be owner or maintainer of the mod.
        required: true
    MODBROWSERPASSPHRASE:
        description: Mod Browser Passphrase corresponding to the provided steamid64. Please make sure to use the Secrets in Github, do not write your passphrase in plain text in your workflow file.
        required: true
    MODNAME:
        description: The internal name of the mod.
        required: true

runs:
  using: "composite"
  steps: 
    - name: Determine if build.txt is newer than Mod Browser
      run: python $GITHUB_ACTION_PATH/CheckBuildTxtVersion.py
      shell: bash
      env:
        INPUT_STEAMID64: ${{ inputs.STEAMID64 }}
        INPUT_MODBROWSERPASSPHRASE: ${{ inputs.MODBROWSERPASSPHRASE }}
        INPUT_MODNAME: ${{ inputs.MODNAME }}
    - name: Build Mod
      run: |
        if [ -z "$INPUT_MODNAME" ]; then
          echo "MODNAME Not provided, mod publish failure."
          exit
        fi
        echo INPUT_MODNAME is $INPUT_MODNAME
        echo pwd is: ${PWD}
        echo ls -l is:
        ls -l
        echo CD to Home
        cd $HOME
        mkdir tModLoader
        cd tModLoader
        echo Downloading tModLoader
        curl -s -L https://github.com/tModLoader/tModLoader/releases/download/v0.11.7.8/tModLoader.Windows.v0.11.7.8.zip -o tModLoader.zip
        unzip -q tModLoader.zip
        echo Downloading ModCompile
        curl -s -L https://github.com/tModLoader/tModLoader/releases/download/v0.11.7.8/ModCompile_FNA.zip -o ModCompile.zip
        unzip -q ModCompile.zip -d ./ModCompile
        touch savehere.txt
        echo Installing XNA
        curl -s -L https://download.microsoft.com/download/5/3/A/53A804C8-EC78-43CD-A0F0-2FB4D45603D3/xnafx40_redist.msi -O
        msiexec //i xnafx40_redist.msi //quiet
        echo XNA Installed
        mkdir -p ModLoader/Mod\ Sources/
        echo pwd is: ${PWD}
        echo ls -l is:
        ls -l
        echo Copy Workspace to correct foldername for build
        cp -r $GITHUB_WORKSPACE ModLoader/Mod\ Sources/$INPUT_MODNAME
        cd ModLoader/Mod\ Sources/$INPUT_MODNAME
        ls -l
        cd ../../..
        echo pwd is: ${PWD}
        echo Building Mod
        ls -l
        echo Initialize tModLoader.targets
        ./tModLoaderServer -build ModLoader/Mod\ Sources/$INPUT_MODNAME
        echo Build XNA dll
        nuget restore
        msbuild
        echo Build tmod file
        ./tModLoaderServer -build ModLoader/Mod\ Sources/$INPUT_MODNAME -eac ModLoader/Mod\ Sources/$INPUT_MODNAME/bin/Debug/net45/$INPUT_MODNAME.dll -unsafe false
        echo Done Building
        cd ModLoader/Mods
        ls -l
      shell: bash
      env:
        INPUT_STEAMID64: ${{ inputs.STEAMID64 }}
        INPUT_MODBROWSERPASSPHRASE: ${{ inputs.MODBROWSERPASSPHRASE }}
        INPUT_MODNAME: ${{ inputs.MODNAME }}
    - name: Publish Mod if newer
      run: |
        if [ "$PUBLISH_NEEDED" != "yes" ]; then
          echo "Publish Not Needed, skipping step."
          exit
        fi
        echo PUBLISH_NEEDED is $PUBLISH_NEEDED
        cd ../..
        echo Publish Mod
        ./tModLoaderServer -publish $INPUT_MODNAME -passphrase $INPUT_MODBROWSERPASSPHRASE -steamid64 $INPUT_STEAMID64
        echo Publish complete
      shell: bash
      env:
        INPUT_STEAMID64: ${{ inputs.STEAMID64 }}
        INPUT_MODBROWSERPASSPHRASE: ${{ inputs.MODBROWSERPASSPHRASE }}
        INPUT_MODNAME: ${{ inputs.MODNAME }}

branding:
    icon: server
    color: blue
